use_frameworks!

def magpie_pods
  pod 'Magpie/HIPAPI', :path => '../'
end

target 'Magpie_Example' do
  platform :ios, '12.4'

  magpie_pods
end

target 'Magpie_Example (Mac)' do
  platform :macos, '10.15'

  magpie_pods
end

target 'Magpie_Tests' do
  platform :ios, '12.4'
  inherit! :search_paths

  magpie_pods
end
