use_frameworks!
platform :ios, '11.0'

target 'Magpie_Example' do
  pod 'Magpie/Core', :path => '../'
  pod 'Magpie/Alamofire', :path => '../'
  pod 'Magpie/HIPAuthorization', :path => '../'
  pod 'Magpie/HIPExceptions', :path => '../'

  target 'Magpie_Tests' do
    inherit! :search_paths
  end
end
